services:
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    # DBが起動してから起動するように設定
#    depends_on:
#      - "db"
#    links:
#      - "db"
  db:
    image: mysql:8.0.23
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todo
    # https://stackoverflow.com/questions/55559386/how-to-fix-mbind-operation-not-permitted-in-mysql-error-log
    cap_add:
      - SYS_NICE
